version: '3.7'

services:
  academia-student-db:
    image: mysql:8.0.16
    container_name: academia-student-db
    ports:
      - '3301:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: academia_student_db
    volumes:
      - academia-student-data:/var/lib/mysql
    networks:
      - student-net

  academia-course-db:
    image: mysql:8.0.16
    container_name: academia-course-db
    ports:
      - '3302:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: academia_course_db
    volumes:
      - academia-course-data:/var/lib/mysql
    networks:
      - course-net

  academia-result-db:
    image: mysql:8.0.16
    container_name: academia-result-db
    ports:
      - '3303:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: academia_result_db
    volumes:
      - academia-result-data:/var/lib/mysql
    networks:
      - result-net

volumes:
  academia-student-data:
  academia-course-data:
  academia-result-data:

networks:
  student-net:
    driver: bridge
  course-net:
    driver: bridge
  result-net:
    driver: bridge

