version: '3.7'

services:

  student-db:
    image: postgres:12.2
    hostname: student-postgres
    container_name: academia-student-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academia-student-db
    ports:
      - '5433:5432'
    volumes:
      - student-postgres-data:/var/lib/postgresql/data
    networks:
      - academia-student-net

  course-db:
    image: postgres:12.2
    hostname: course-postgres
    container_name: academia-course-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academia-course-db
    ports:
      - '5434:5432'
    volumes:
      - course-postgres-data:/var/lib/postgresql/data
    networks:
      - academia-course-net

  result-db:
    image: postgres:12.2
    hostname: result-postgres
    container_name: academia-result-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academia-result-db
    ports:
      - '5435:5432'
    volumes:
      - result-postgres-data:/var/lib/postgresql/data
    networks:
      - academia-result-net

  academia-backoffice-redis-cache:
    image: redis
    hostname: backoffice-redis
    container_name: academia-redis-cache
    ports:
      - "6379:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
    volumes:
      - backoffice-redis-data
    networks:
      - academia-backoffice-net

volumes:
  student-postgres-data:
  course-postgres-data:
  result-postgres-data:
  backoffice-redis-data:

networks:
  academia-student-net:
    driver: bridge
  academia-course-net:
    driver: bridge
  academia-result-net:
    driver: bridge
  academia-backoffice-net:
    driver: bridge

