
#logging config
logging:
  level:
    org:
      springframework:
        web: DEBUG

#redis
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 120
  cache:
    redis:
      time-to-live: 2m

