
#logging config
logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  #postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/academia-student-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  #jpa properties
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: academia_student_schema
        format_sql: true
    show-sql: true

  #flyway properties
  flyway:
    enabled: true
    password: postgres
    schemas:
      - academia_student_schema
    table: flyway_schema_history
