SET SCHEMA 'academia_student_schema';

DROP TABLE IF EXISTS STUDENT CASCADE
;

CREATE TABLE STUDENT
(
    ID bigint NOT NULL,
    STUDENT_IDENTIFICATION_NUMBER varchar(15) UNIQUE NOT NULL,
    FIRST_NAME varchar(50) NULL,
    LAST_NAME varchar(50) NULL,
    EMAIL varchar(100) NULL,
    BIRTH_DATE timestamp with time zone NULL,
    REGISTRATION_DATE timestamp with time zone NULL
);

ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT
    PRIMARY KEY (ID)
;

CREATE INDEX IX_STUDENT_SIN ON STUDENT (STUDENT_IDENTIFICATION_NUMBER ASC)
;

CREATE SEQUENCE STUDENT_ID_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 1
;