SET SCHEMA 'academia_course_schema';

DROP TABLE IF EXISTS COURSE CASCADE
;

CREATE TABLE COURSE (
    ID bigint NOT NULL,
    COURSE_IDENTIFICATION_NUMBER varchar(15) UNIQUE NOT NULL,
    TITLE varchar(255) NULL,
    MANDATORY boolean,
    CREATION_DATE timestamp with time zone NULL );

ALTER TABLE COURSE ADD CONSTRAINT PK_COURSE
    PRIMARY KEY (ID)
;

CREATE INDEX IX_COURSE_CIN ON COURSE (COURSE_IDENTIFICATION_NUMBER ASC)
;

CREATE SEQUENCE COURSE_ID_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 1
;